config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    passwords: 'public/passwords' # パスワード再設定用
  }

  devise_scope :user do
    root to: 'home#index'
    get 'users/delete_account', to: 'users/registrations#delete_account', as: 'delete_account'
    delete 'users/destroy_account', to: 'users/registrations#destroy_account', as: 'destroy_account'
    get 'goodbye', to: 'users/registrations#goodbye', as: 'goodbye'
  end

  resources :care_contents, only: [:new, :create, :edit, :update] do
    member do
      get 'generate_pdf'
    end
  end

  resources :qr_codes, only: [:show, :index]

  get 'qr_codes/:id/scan', to: 'qr_codes#scan', as: 'scan_qr_code'

  # LINEログインのルートを追加
  get 'line_login_api/login', to: 'line_login_api#login'
  get 'line_login_api/callback', to: 'line_login_api#callback'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.present?
      Rails.logger.debug "Current user: #{current_user.inspect}"
      @care_content = current_user.care_content
      @qr_code = current_user.qr_code
      Rails.logger.debug "Care content: #{@care_content.inspect}"
      Rails.logger.debug "QR code: #{@qr_code.inspect}"
    else
      Rails.logger.debug "No current user"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="content">
  <% if @care_content.present? %>
    <% if @care_content.preferred_name.present? %>
      <p class="highlighted"><strong>私の名前は、<br> <%= @care_content.preferred_name %> です</strong></p>
      <p class="highlighted-text"><strong>今困っていますので、助けてください</strong></p>
    <% end %>
  <% end %>

<div class="qr-code-wrapper">
  <div><p class="highlight">QRコードを読み込んでください</p></div>
  <div class="qr-code-container">
    <div class="qr-code-section">
      <% if @qr_code.present? %>
        <%= image_tag qr_code_path(@qr_code, format: :png), class: 'qr-code' %>
      <% else %>
        <p>QRコードが登録されていません。</p>
      <% end %>
      <!-- <span class="custom-size">読み込んでください</span> -->

    </div>
    <div class="qr-code-message">
      <p class="info">➀左のQRコードを<br>読み込む</p>
      <p class="info">➁お手伝いを<br>お願いします</p>
    </div>
  </div>
</div>


<div class="links-section">
  <%= link_to edit_care_content_path(@care_content), class: "btn btn-primary icon-link" do %>
    <img src="<%= asset_path('pen2_icon.svg') %>" alt="Edit Icon" class="icon">
    <span><strong>緊急時の表示内容</strong></span>
  <% end %>
  
  <%= link_to "#", class: "btn btn-primary icon-link",id: "printer-button" do %>
    <img src="<%= asset_path('print_icon.svg') %>" alt="Print Icon" class="icon">
    <span><strong>画面印刷</strong></span>
  <% end %>
  
  <%= link_to "tel:#{@care_content.phone_number}", class: "btn btn-primary icon-link phone-link" do %>
    <img src="<%= asset_path('phone2_icon.svg') %>" alt="Phone Icon" class="icon">
    <span><strong>緊急連絡先に電話する</strong></span>
  <% end %>

  <%= link_to edit_user_registration_path, class: "btn btn-primary icon-link" do %>
    <img src="<%= asset_path('account2_icon.svg') %>" alt="Profile Icon" class="icon">
    <span><strong>アカウント設定</strong></span>
  <% end %>

  <!-- <% if user_signed_in? %>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, data: { confirm: 'ログアウトしますか？' } %>
  <% end %> -->
 
</div>